# Generated by Django 4.2 on 2026-04-26 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StegoOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('encode', 'Encode'), ('decode', 'Decode')], max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('message_length', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='success', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stego_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stego_operation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stegooperation',
            index=models.Index(fields=['user', '-created_at'], name='stego_opera_user_id_6848d3_idx'),
        ),
        migrations.AddIndex(
            model_name='stegooperation',
            index=models.Index(fields=['operation_type'], name='stego_opera_operati_d68b73_idx'),
        ),
    ]
